import {
	FaGithub,
	FaInstagram,
	FaLinkedin,
	FaPinterest,
	FaRegBookmark,
	FaRegUser,
	FaSteam,
	FaTwitch,
} from 'react-icons/fa';
import { IoGridOutline } from 'react-icons/io5';
import type { Project } from '../types';


export const personalInfo = {
	name: 'Devmike117',
	age: 21,
	location: 'México, Estado de México',
	occupation: 'Full-Stack Developer & Traveling Tech Enthusiast',
	overview:
		'Estudiante de Ing. en Sistemas Computacionales. Trabajo en desarrollo web, software y temas de ciberseguridad.',
	hobbies: [
		'Hobbies:',
		'Viajar a distintas partes.',
		'Tocar instrumentos: Guitarra eléctrica, Bateria y Piano.',
		'Tener tiempo de calidad con amig@s y familia.',
		'Prácticar deportes: Skateboarding y BMX.',
		'Asistir a conciertos de mis bandas favoritas ♡.',

		// Y que viva the neighbourhood jaja ok no, bueno si pero no lo pongo :D
	],
	otherLinks: [
		{
			id: 1,
			name: 'Mi Portfolio',
			url: 'https://devmikeportfolio.netlify.app/',

		},
	],
	song: {
    title: 'Stuck with Me',
    artist: 'The Neighbourhood',
    url: 'https://raw.githubusercontent.com/Devmike117/music1/main/Stuck%20with%20Me%20-%20The%20Neighbourhood.mp3', 
  },
	socialLinks: [
		{
			id:1,
			name: 'Instagram',
			url: 'https://www.instagram.com/devmike117/',
			icon: <FaInstagram size={30} />,
		},
		{
			id: 2,
			name: 'Pinterest',
			url: 'https://www.pinterest.com/devmike117/',
			icon: <FaPinterest size={30} />,
		},
		{
			id: 3,
			name: 'GitHub',
			url: 'https://github.com/Devmike117',
			icon: <FaGithub size={30} />,
		},
		{
			id: 4,
			name: 'LinkedIn',
			url: 'https://www.linkedin.com/in/miguelgabrielhndz/',
			icon: <FaLinkedin size={30} />,
		},
		{
			id: 5,
			name: 'Steam',
			url: 'https://steamcommunity.com/id/mikedarkness',
			icon: <FaSteam size={30} />,	
		},
		{
			id: 6,
			name: 'Twitch',
			url: 'https://www.twitch.tv/devmike117',
			icon: <FaTwitch size={30} />,
		},
	],
	photoSrc: '/foto.webp',
};

export const tabs = [
	{
		id: 1,
		name: 'Proyectos',
		icon: IoGridOutline,
	},
	{
		id: 2,
		name: 'Experiencia',
		icon: FaRegBookmark,
	},
	{
		id: 3,
		name: 'Habilidades',
		icon: FaRegUser,
	},
];

export const projects: Project[] = [
	{
		id: 1,
		name: 'Medi-IA',
		description:
			'Herramienta web para consulta farmacológica Detecta detalles de medicamentos capturados desde la cámara y permite búsqueda por voz. Utiliza inteligencia artificial para extraer información relevante en tiempo real, facilitando consultas rápidas y mejorando la accesibilidad en entornos médicos.',
		technologies: [
			'JavaScript',
			'HTML5',
			'CSS3',
			'OCR.space',
			'Node.js',
			'emailjs',
			'localStorage',
		],
		projectUrl: 'https://medi-ia.netlify.app/',
		githubUrl: 'https://github.com/Devmike117/medi-IA',
		imageSrc: '/project1.jpg',
	},
	{
		id: 2,
		name: 'Quitafondo',
		description:
			'Aplicación de escritorio que elimina fondos de imágenes automáticamente y sin conexión, usando redes neuronales. Ofrece edición manual, compatibilidad con múltiples formatos y preserva la calidad sin subir archivos a terceros.',
		technologies: [
			'Python',
			'tkinter',
			'rembg',
			'Pillow',
			'pyinstaller',
		],
		projectUrl: 'https://github.com/Devmike117/eliminar-fondo-de-imagenes/releases/tag/vv1.0',
		githubUrl: 'https://github.com/Devmike117/eliminar-fondo-de-imagenes',
		imageSrc: '/project2.jpg',
	},
	{
		id: 3,
		name: 'Verificador de correos electrónicos',
		description:
			'Herramienta de escritorio en Python que audita direcciones de correo en tiempo real. Evalúa sintaxis, servidores, autenticación y posibles intentos de phishing, todo de forma local y sin comprometer la privacidad del usuario.',
		technologies: [
			'Python',
			'tkinter',
			'dns.resolver',
			're',
			'socket',
			'smtplib',
			'pyinstaller',
		],
		projectUrl: 'https://github.com/Devmike117/verificar-correos-electronicos/releases/tag/new',
		githubUrl: 'https://github.com/Devmike117/verificar-correos-electronicos',
		imageSrc: '/project3.jpg',
	},
	{
		id: 4,
		name: 'Sistema de Cifrado Web para PDFs',
		description:
			'Sistema que permite cifrar archivos PDF utilizando algoritmos como ECC, RSA, AES y ChaCha20. Ideal para proteger documentos sensibles en contextos educativos, profesionales o personales.',
		technologies: [
			'Python',
			'Flask',
			'HTML5',
			'CSS3',
			'tkinter',
			'PyCryptodome',
			'cryptography',
			'Scripts personalizados',
		],

		projectUrl: '#',
		githubUrl: 'https://github.com/Devmike117/Sistema-de-Cifrado-Web-para-PDFs',
		imageSrc: '/project4.png',
	},
	{
		id: 5,
		name: 'Modelo de Detección de Rostros',
		description:
			'Identifica rostros humanos en tiempo real y en imágenes estáticas usando algoritmos Haar Cascade y redes neuronales. Funciona localmente y es útil para pruebas biométricas básicas y sistemas de autenticación.',
		technologies: [
			'Python',
			'OpenCV',
			'tkinter',
			'CNN',
			'CMake',
			'HTML5',
			'CSS3',
			'JavaScript',
		],
		projectUrl: '#',
		githubUrl: 'https://github.com/Devmike117/modelo-deteccion-de-rostros',
		imageSrc: '/project5.png',
	},
	{
		id: 6,
		name: 'Generador de Códigos QR',
		description:
			'Herramienta que permite crear códigos QR personalizados en segundos, a partir de texto, enlaces o datos de contacto. Funciona sin conexión a internet y es ideal para compartir información de forma rápida y moderna.',
		technologies: [
			'Python',
			'tkinter',
			'qrcode',
			'Pillow',
			'pyinstaller',
		],
		projectUrl: 'https://github.com/Devmike117/Generador-codigos-QR/releases/tag/VV1.0',
		githubUrl: 'https://github.com/Devmike117/Generador-codigos-QR',
		imageSrc: '/project6.png',
	},
];

export const experience = [
	{
		id: 1,
		position: 'Front-end developer',
		timeRange: 'Sep 2025 – Actual',
		companyName: 'Gobierno de México. Centro de comando y control c2.',
		companyLocation: 'México',
		description:
			'Residencia profesional donde se está desarrollando un sistema de arrestos administrativos para centros de comando y control.\n\n' +
			'• El sistema permite registrar, buscar y gestionar personas arrestadas mediante biometría facial y escaneo de huellas, generando plantillas cifradas que evitan duplicidades.\n\n' +
			'• Su arquitectura elimina registros manuales, reduce errores y agiliza decisiones operativas.\n\n' +
			'• Detecta reincidencias con el algoritmo de reconocimiento facial, actualiza historiales y genera reportes PDF con firma digital y código QR único.\n\n' +
			'• Dashboard analítico para visualizar estadísticas en tiempo real y control de acceso para administradores.\n\n' +
			'• Operación local bajo estándares de seguridad y privacidad, cumpliendo con normativas nacionales e internacionales en protección de datos personales y biométricos.',

		technologiesUsed: [
			'React',
			'Chart.js',
			'react-chartjs-2',
			'Axios JS',
			'QRCode.react',
			'Node.js',
			'Express',
			'PostgreSQL',
			'pgAdmin',
			'Multer',
			'PDFKit',
			'bcrypt',
			'CORS',
			'FastAPI',
			'DeepFace',
			'TensorFlow / Keras',
			'OpenCV',
			'NumPy',
			'Docker',
			'Docker Compose',
			'Git',
			'GitHub',
			'Python',
			'tailwind css',
			'JavaScript',
			'ISO/IEC 27001',
			'ISO/IEC 27701',
			'ISO/IEC 29100',
			'BD de Estados de la República Mexicana propia en formato .JSON',
			'Ley Federal de Protección de Datos Personales (México)',
		],
	},
	{
		id: 2,
		position: 'Student Assembly Developer',
		timeRange: 'Jul 2022 – Jul 2024',
		companyName: 'Microsoft.',
		companyLocation: 'Remoto',
		description:
			'Participación en el programa Student Assembly de Microsoft, donde accedi a las últimas tecnologías y herramientas para desarrollar soluciones innovadoras. Trabajé en proyectos colaborativos, mejorando mis habilidades técnicas y de trabajo en equipo en un entorno profesional.',
		technologiesUsed: ['Azure', 'Visual Studio', 'GitHub', 'GitHub Actions'],
	},
	{
		id: 3,
		position: 'Developer videogame',
		timeRange: '2022 – 2022',
		companyName: 'Ugame Studio.',
		companyLocation: 'Online',
		description:
			'Desarrollo de un videojuego estilo Doom con mecánicas de roguelike y survival horror en Unity. Implementación de sistemas de combate, generación procedural de niveles y gestión de recursos para crear una experiencia inmersiva y desafiante. Como parte de acceso previo a su tecnología',
		technologiesUsed: ['Unity', 'C#', 'Visual Studio', 'GitHub'],
	},
];

export const skills = [
	{
		id: 1,
		imageSrc: '/react.png',
		technologyName: 'React',
		level: 'Intermedio',
		context: 'Frontend',
		bgColor: '#E1F5FE',
		borderColor: '#81D4FA',
	},
	{
		id: 2,
		imageSrc: '/nextjs.png',
		technologyName: 'Next.js',
		level: 'Básico',
		context: 'Full-Stack',
		bgColor: '#F5F5F5',
		borderColor: '#BDBDBD',
	},
	{
		id: 3,
		imageSrc: '/nodejs.png',
		technologyName: 'Node.js',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E8F5E8',
		borderColor: '#81C784',
	},
	{
		id: 4,
		imageSrc: '/nestjs.png',
		technologyName: 'NestJS',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#FCE4EC',
		borderColor: '#F48FB1',
	},
	{
		id: 5,
		imageSrc: '/gsap.png',
		technologyName: 'GSAP',
		level: 'Intermedio',
		context: 'Animations',
		bgColor: '#F1F8E9',
		borderColor: '#AED581',
	},
	{
		id: 6,
		imageSrc: '/tailwindcss.png',
		technologyName: 'Tailwind CSS',
		level: 'Avanzado',
		context: 'UI/UX',
		bgColor: '#E0F7FA',
		borderColor: '#80DEEA',
	},
	{
		id: 7,
		imageSrc: '/typescript.png',
		technologyName: 'TypeScript',
		level: 'Avanzado',
		context: 'Language',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 8,
		imageSrc: '/javascript.png',
		technologyName: 'JavaScript',
		level: 'Avanzado',
		context: 'Language',
		bgColor: '#FFFDE7',
		borderColor: '#FFF176',
	},
	{
		id: 9,
		imageSrc: '/python.png',
		technologyName: 'Python',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 10,
		imageSrc: '/rust.png',
		technologyName: 'Rust',
		level: 'Básico',
		context: 'Systems',
		bgColor: '#FFF3E0',
		borderColor: '#FFCC80',
	},
	{
		id: 11,
		imageSrc: '/flutter.png',
		technologyName: 'Flutter',
		level: 'Intermedio',
		context: 'Mobile',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 12,
		imageSrc: '/vuejs.png',
		technologyName: 'Vue.js',
		level: 'Intermedio',
		context: 'Frontend',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 13,
		imageSrc: '/graphql.png',
		technologyName: 'GraphQL',
		level: 'Intermedio',
		context: 'API',
		bgColor: '#FCE4EC',
		borderColor: '#F8BBD9',
	},
	{
		id: 14,
		imageSrc: '/docker.png',
		technologyName: 'Docker',
		level: 'Intermedio',
		context: 'DevOps',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 15,
		imageSrc: '/aws.png',
		technologyName: 'AWS',
		level: 'Intermedio',
		context: 'Cloud',
		bgColor: '#FFF8E1',
		borderColor: '#FFCC02',
	},
	{
		id: 16,
		imageSrc: '/firebase.png',
		technologyName: 'Firebase',
		level: 'Básico',
		context: 'Backend',
		bgColor: '#FFF8E1',
		borderColor: '#FFD54F',
	},
	{
		id: 17,
		imageSrc: '/googlecloud.png',
		technologyName: 'Google Cloud',
		level: 'Básico',
		context: 'Cloud',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 18,
		imageSrc: '/mongodb.png',
		technologyName: 'MongoDB',
		level: 'Intermedio',
		context: 'Database',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 19,
		imageSrc: '/postgresql.png',
		technologyName: 'PostgreSQL',
		level: 'Intermedio',
		context: 'Database',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 20,
		imageSrc: '/unity.webp',
		technologyName: 'Unity',
		level: 'Intermedio',
		context: 'Game Dev',
		bgColor: '#FAFAFA',
		borderColor: '#E0E0E0',
	},
	{
		id: 21,
		imageSrc: '/csharp.png',
		technologyName: 'C#',
		level: 'Básico',
		context: 'Language',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 22,
		imageSrc: '/storybook.png',
		technologyName: 'Storybook',
		level: 'Básico',
		context: 'UI Tools',
		bgColor: '#FCE4EC',
		borderColor: '#F8BBD9',
	},
	{
		id: 23,
		imageSrc: '/fastapi.png',
		technologyName: 'FastAPI',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E0F2F1',
		borderColor: '#80CBC4',
	},
	{
		id: 24,
		imageSrc: '/elasticsearch.png',
		technologyName: 'Elasticsearch',
		level: 'Básico',
		context: 'Search',
		bgColor: '#E0F7FA',
		borderColor: '#80DEEA',
	},
	{
		id: 25,
		imageSrc: '/netlify.png',
		technologyName: 'Netlify',
		level: 'Avanzado',
		context: 'Deployment',
		bgColor: '#E8F5E8',
		borderColor: '#81C784',
	},
	{
		id : 26,
		imageSrc: '/git.png',
		technologyName: 'Git',
		level: 'Avanzado',
		context: 'version control',
		bgColor: '#F3E5F5',
		borderColor: '#E1BEE7',
	},
	{
		id: 27,
		imageSrc: '/githubb.png',
		technologyName: 'GitHub',
		level: 'Avanzado',
		context: 'version control',
		bgColor: '#E8E8E8',
		borderColor: '#B0B0B0',
	}
];
