import {
	FaGithub,
	FaInstagram,
	FaLinkedin,
	FaPinterest,
	FaRegBookmark,
	FaRegUser,
	FaSteam,
} from 'react-icons/fa';
import { IoGridOutline } from 'react-icons/io5';
import type { Project } from '../types';


export const personalInfo = {
	name: 'Devmike117',
	age: 21,
	location: 'México, Estado de México',
	occupation: 'Full-Stack Developer & Traveling Tech Enthusiast',
	overview:
		'Estudiante de Ingeniería en Sistemas Computacionales (a pocos meses de graduarme), especializado en desarrollo web, software y ciberseguridad. Domino tecnologías  de front-end y back-end, buscando proyectos que me reten tanto a nivel personal como profesional.',
	otherLinks: [
		{
			id: 1,
			name: 'Mi Portfolio',
			url: 'https://portfoliodevmike117.netlify.app/',

		},
	],
	song: {
    title: 'Birds of a Feather',
    artist: 'Billie Eilish',
    url: 'https://raw.githubusercontent.com/Devmike117/music1/main/BIRDS%20OF%20A%20FEATHER%20-%20Billie%20Eilish.mp3', 
  },
	socialLinks: [
		{
			id:1,
			name: 'Instagram',
			url: 'https://www.instagram.com/devmike117/',
			icon: <FaInstagram size={26} />,
		},
		{
			id: 2,
			name: 'Pinterest',
			url: 'https://www.pinterest.com/devmike117/',
			icon: <FaPinterest size={26} />,
		},
		{
			id: 3,
			name: 'GitHub',
			url: 'https://github.com/Devmike117',
			icon: <FaGithub size={26} />,
		},
		{
			id: 4,
			name: 'LinkedIn',
			url: 'https://www.linkedin.com/in/miguelgabrielhndz/',
			icon: <FaLinkedin size={26} />,
		},
		{
			id: 5,
			name: 'Steam',
			url: 'https://steamcommunity.com/id/mikedarkness',
			icon: <FaSteam size={26} />,
		},
	],
	phoneNumber: '+',
	photoSrc: '/foto.webp',
};

export const tabs = [
	{
		id: 1,
		name: 'Proyectos',
		icon: IoGridOutline,
	},
	{
		id: 2,
		name: 'Experiencia',
		icon: FaRegBookmark,
	},
	{
		id: 3,
		name: 'Habilidades',
		icon: FaRegUser,
	},
];

export const projects: Project[] = [
	{
		id: 1,
		name: 'Medi-IA',
		description:
			'',
		technologies: [
			'1',
			'2',
			'3',
			'4',
			'5',
			'6',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project1.jpg',
	},
	{
		id: 2,
		name: 'Project 2',
		description:
			'Descripción próximamente',
		technologies: [
			'Next.js',
			'TensorFlow.js',
			'Socket.IO',
			'TypeScript',
			'Supabase',
			'Docker',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project2.jpg',
	},
	{
		id: 3,
		name: 'Project 3',
		description:
			'Descripción próximamente',
		technologies: [
			'Flutter',
			'Firebase (Firestore, Auth)',
			'GitHub Actions',
			'Node.js',
			'NestJS',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project3.jpg',
	},
	{
		id: 4,
		name: 'Project 4',
		description:
			'Descripción próximamente',
		technologies: [
			'Unity',
			'C#',
			'REST API (Arasaac)',
			'PlayFab',
			'GSAP',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project4.png',
	},
	{
		id: 5,
		name: 'Project 5',
		description:
			'Descripción próximamente',
		technologies: [
			'Python',
			'FastAPI',
			'Elasticsearch',
			'Vue.js',
			'Tailwind CSS',
			'OpenAI API',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project5.png',
	},
	{
		id: 6,
		name: 'Project 6',
		description:
			'Descripción próximamente',
		technologies: [
			'Gatsby',
			'Mapbox GL',
			'Contentful',
			'Cloudinary',
			'Node.js',
			'AWS Lambda',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project6.png',
	},
];

export const experience = [
	{
		id: 1,
		position: 'Frontend Developer',
		timeRange: 'Sep 2025 – Actual',
		companyName: 'Comando y centro de control (C2) .',
		companyLocation: 'Mexico, Estado de México',
		description:
			'Residencia profesional donde se esta desarrollando un sistema de arrestos. La arquitectura está diseñada para eliminar la dependencia de registros manuales, reduciendo errores humanos y acelerando la toma de decisiones operativas. Gracias a una interfaz accesible y a la integración de algoritmos de reconocimiento facial, el sistema permite detectar si una persona ya ha sido detenida anteriormente y actualizar su historial sin intervención manual.',
		technologiesUsed: [
			'Node.js',
			'MongoDB',
			'Docker',
			'Deepsearch',
			'React',
			'Deepface',
			'OpenCV',
			'Microservicios propios',
		],
	},
	{
		id: 2,
		position: 'Student Assembly Developer',
		timeRange: 'Jul 2022 – Jul 2024',
		companyName: 'Microsoft.',
		companyLocation: 'Remoto',
		description:
			'Participación en el programa Student Assembly de Microsoft, donde accedi a las últimas tecnologías y herramientas para desarrollar soluciones innovadoras. Trabajé en proyectos colaborativos, mejorando mis habilidades técnicas y de trabajo en equipo en un entorno profesional.',
		technologiesUsed: ['Azure', 'Visual Studio', 'GitHub', 'GitHub Actions'],
	},
	{
		id: 3,
		position: 'Developer videogame',
		timeRange: '2022 – 2022',
		companyName: 'Ugame Studio.',
		companyLocation: 'Online',
		description:
			'Desarrollo de un videojuego estilo Doom con mecánicas de roguelike y survival horror en Unity. Implementación de sistemas de combate, generación procedural de niveles y gestión de recursos para crear una experiencia inmersiva y desafiante. Como parte de acceso previo a su tecnología',
		technologiesUsed: ['Unity', 'C#', 'Visual Studio', 'GitHub'],
	},
];

export const skills = [
	{
		id: 1,
		imageSrc: '/react.png',
		technologyName: 'React',
		level: 'Intermedio',
		context: 'Frontend',
		bgColor: '#E1F5FE',
		borderColor: '#81D4FA',
	},
	{
		id: 2,
		imageSrc: '/nextjs.png',
		technologyName: 'Next.js',
		level: 'Básico',
		context: 'Full-Stack',
		bgColor: '#F5F5F5',
		borderColor: '#BDBDBD',
	},
	{
		id: 3,
		imageSrc: '/nodejs.png',
		technologyName: 'Node.js',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E8F5E8',
		borderColor: '#81C784',
	},
	{
		id: 4,
		imageSrc: '/nestjs.png',
		technologyName: 'NestJS',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#FCE4EC',
		borderColor: '#F48FB1',
	},
	{
		id: 5,
		imageSrc: '/gsap.png',
		technologyName: 'GSAP',
		level: 'Intermedio',
		context: 'Animations',
		bgColor: '#F1F8E9',
		borderColor: '#AED581',
	},
	{
		id: 6,
		imageSrc: '/tailwindcss.png',
		technologyName: 'Tailwind CSS',
		level: 'Avanzado',
		context: 'UI/UX',
		bgColor: '#E0F7FA',
		borderColor: '#80DEEA',
	},
	{
		id: 7,
		imageSrc: '/typescript.png',
		technologyName: 'TypeScript',
		level: 'Avanzado',
		context: 'Language',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 8,
		imageSrc: '/javascript.png',
		technologyName: 'JavaScript',
		level: 'Avanzado',
		context: 'Language',
		bgColor: '#FFFDE7',
		borderColor: '#FFF176',
	},
	{
		id: 9,
		imageSrc: '/python.png',
		technologyName: 'Python',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 10,
		imageSrc: '/rust.png',
		technologyName: 'Rust',
		level: 'Básico',
		context: 'Systems',
		bgColor: '#FFF3E0',
		borderColor: '#FFCC80',
	},
	{
		id: 11,
		imageSrc: '/flutter.png',
		technologyName: 'Flutter',
		level: 'Intermedio',
		context: 'Mobile',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 12,
		imageSrc: '/vuejs.png',
		technologyName: 'Vue.js',
		level: 'Intermedio',
		context: 'Frontend',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 13,
		imageSrc: '/graphql.png',
		technologyName: 'GraphQL',
		level: 'Intermedio',
		context: 'API',
		bgColor: '#FCE4EC',
		borderColor: '#F8BBD9',
	},
	{
		id: 14,
		imageSrc: '/docker.png',
		technologyName: 'Docker',
		level: 'Intermedio',
		context: 'DevOps',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 15,
		imageSrc: '/aws.png',
		technologyName: 'AWS',
		level: 'Intermedio',
		context: 'Cloud',
		bgColor: '#FFF8E1',
		borderColor: '#FFCC02',
	},
	{
		id: 16,
		imageSrc: '/firebase.png',
		technologyName: 'Firebase',
		level: 'Básico',
		context: 'Backend',
		bgColor: '#FFF8E1',
		borderColor: '#FFD54F',
	},
	{
		id: 17,
		imageSrc: '/mongodb.png',
		technologyName: 'MongoDB',
		level: 'Intermedio',
		context: 'Database',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 18,
		imageSrc: '/postgresql.png',
		technologyName: 'PostgreSQL',
		level: 'Intermedio',
		context: 'Database',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 19,
		imageSrc: '/unity.webp',
		technologyName: 'Unity',
		level: 'Intermedio',
		context: 'Game Dev',
		bgColor: '#FAFAFA',
		borderColor: '#E0E0E0',
	},
	{
		id: 20,
		imageSrc: '/csharp.png',
		technologyName: 'C#',
		level: 'Básico',
		context: 'Language',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 21,
		imageSrc: '/storybook.png',
		technologyName: 'Storybook',
		level: 'Básico',
		context: 'UI Tools',
		bgColor: '#FCE4EC',
		borderColor: '#F8BBD9',
	},
	{
		id: 22,
		imageSrc: '/fastapi.png',
		technologyName: 'FastAPI',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E0F2F1',
		borderColor: '#80CBC4',
	},
	{
		id: 23,
		imageSrc: '/elasticsearch.png',
		technologyName: 'Elasticsearch',
		level: 'Básico',
		context: 'Search',
		bgColor: '#E0F7FA',
		borderColor: '#80DEEA',
	},
	{
		id: 24,
		imageSrc: '/netlify.png',
		technologyName: 'Netlify',
		level: 'Avanzado',
		context: 'Deployment',
		bgColor: '#E8F5E8',
		borderColor: '#81C784',
	},
];
